networks:
  my-network:
    driver: bridge

services:
  postgres:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 20
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: userok
      POSTGRES_DB: company_db
    ports:
      - "5432:5432"
    networks:
      - my-network

  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: config-server
    ports:
      - "8888"
    container_name: config-server
    healthcheck:
      test: ["CMD", "wget", "-q0-", "http://localhost:8888/actuator/health"]
    depends_on:
      - postgres
    networks:
      - my-network

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: user-service
    environment:
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: userok
      POSTGRES_DB: company_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8101:8101"
    depends_on:
      - postgres
      - eureka-server
    networks:
      - my-network

  company-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: company-service
    environment:
      POSTGRES_USER: userok
      POSTGRES_PASSWORD: userok
      POSTGRES_DB: company_db
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "8102:8102"
    depends_on:
      config-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_started

    networks:
      - my-network

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: eureka-server
    ports:
      - "8761:8761"
    networks:
      - my-network

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - my-network

